dbconnector
semen603089/datatool-db-engine pull request #5
Opened 2022-06-02 20:07 UTC by semen603089

2022-06-04 13:09 UTC, dyakovri reviewed
А вообще мне нравится. Это как раз то, что я имел в виду!
Только файлы и папки называй все в `lowercase_snake_case`, согласно pep8

2022-06-04 13:09 UTC, dyakovri commented on dbengine/settings.py
> +    DB_DSN: AnyUrl
Тут можно использовать `PostgresDsn`
https://pydantic-docs.helpmanual.io/usage/types/#urls

2022-06-07 20:26 UTC, dyakovri requested changes
Хорошо, давай это поправим и посмотрим вместе, как переложить код поаккуратнее

2022-06-07 20:26 UTC, dyakovri commented on dbengine/db_connector/db_connector.py
> +                    self._connection_prod.execute(row.sql_down)
Давай оставим один `execute(self, sql: str)`, который просто в своем соединении запускает переданную SQL строчку. А эту функциональность надо вынести в другое место

2022-06-07 20:26 UTC, dyakovri commented on dbengine/db_connector/db_connector.py
> +        return f'{"ALTER TABLE"} {tablename} ADD COLUMN {columnname} {columntype};'
И все-таки я буду блочить мердж с такими штуками

2022-06-07 20:26 UTC, dyakovri commented on dbengine/methods/branch.py
> +    return tables, columns
Давай перенесем в class Branch и возвращать будем что-нибудь типа 
```python
[
    (table1, (column11, column12, ...)),
    (table2, (column21, column22, ...)),
]
```

UPD: Массив таплов, потому что сущности алхимии, кажется, не хэшируемые и их нельзя использовать как ключи словаря (который, как ты наверняка знаешь, в науке называется HashMap)

2022-06-07 20:26 UTC, dyakovri commented on dbengine/methods/branch.py
> +    return True
Кажется, что тут не надо брать все таблицы в ветке 

Логичнее проитерироваться от головы ветки до момента, где она выходит из мэйна и посмотреть, какие сущности изменились (составить массив этих изменений, например). А потом бежать по мастеру от этого коммита до головы и сделать `raise BranchConflict` если изменение коснулось той же сущности (`if attribute_out .entity in branch_entity_list: raise BranchConflict`)

2022-06-07 20:26 UTC, dyakovri commented on dbengine/methods/branch.py
> +        return None
Кажется, делается в 4 строки и без дублирования кода. Ты же от DbAttributes отнаследовался 
```
anyattr = commit.attribute_id_in or commit.attribute_id_out  # Возьмет первый не None
if not anyattr: 
    return None
return anyattr.type
```

2022-06-07 20:26 UTC, dyakovri commented on dbengine/methods/branch.py
> +
А оно точно надо? И это точно можно сократить как `get_type_of_commit_object`

2022-06-07 20:26 UTC, dyakovri commented on dbengine/methods/table.py
>  ) -> Commit:
Я чувствую здесь очень плохой автоформаттер
Сделай `pip install black && black {путь к файлу}` в консоли
Вообще надо сделать `black .`, но в отдельной ветке, чтобы потом не умереть от количества файлов на ревью

2022-06-07 20:26 UTC, dyakovri commented on dbengine/methods/table.py
> +        logging.error(sqlalchemy.exc.NoResultFound, exc_info=True)
Извините, выгляит пиз**ц
Зачем и что делает?

2022-06-07 20:26 UTC, dyakovri commented on dbengine/models/branch.py
> +def commits_before_commit_in_branch(commit: Commit):
Давай так
`def prev_commits_generator(commit: Commit) -> Iterator[Commit]:`

2022-06-10 03:14 UTC, semen603089 commented on dbengine/methods/branch.py
> +        return None
'int' object has no attribute 'type'

2022-06-10 03:47 UTC, semen603089 commented on dbengine/models/branch.py
> +def commits_before_commit_in_branch(commit: Commit):
я его не использую потом нигде, так что удалил пока что

2022-06-10 04:04 UTC, semen603089 commented on dbengine/methods/table.py
>  ) -> Commit:
сделал в этом файле, во всех остальных потом сделаем в отдельной ветке

2022-06-10 13:55 UTC, semen603089 commented on dbengine/methods/table.py
> +        logging.error(sqlalchemy.exc.NoResultFound, exc_info=True)
убрал эту функциональность в другой метод(+10 строк)

2022-06-11 03:08 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return tables, columns
вот так получается сделал пока что  list[tuple[tuple[DbTable, DbTableAttributes], tuple[tuple[DbColumn, DbColumnAttributes], ...]]]

2022-06-11 03:08 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return tables, columns
ну просто везде атрибуты добавлены

2022-06-13 15:37 UTC, dyakovri requested changes

2022-06-15 16:22 UTC, semen603089 commented on dbengine/db_connector/db_connector.py
> +        self._connect()
поменял на сессию из fastapi

2022-06-15 16:23 UTC, semen603089 commented on dbengine/db_connector/db_connector.py
> +        self._connect()
будем тогда коннектится как в алхимии отдельной командой obj.connect()

2022-06-15 16:25 UTC, semen603089 commented on dbengine/db_connector/db_connector.py
> +            tablename = None
да просто ide так не подчёркивает ахах :))

2022-06-18 19:45 UTC, semen603089 commented
короче, я много что находил, пока что не буду коммитить до интуров ибо надо дебажить и приводить в порядок

2022-07-05 15:57 UTC, semen603089 commented on dbengine/routes/branch.py
> +from dbengine.db_connector.db_connector import PostgreConnector
Это вроде было про импорт PostgreConnector 
Я там дальше написал подключение в зависимости от .env, мб можно сделать его в месте получше

2022-07-05 17:47 UTC, dyakovri requested changes

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/branch.py
> +            raise MergeError
Выглядит оч неоч
Хочется видеть тут

```python
if have_conflicts(branch, session=session):
    raise MergeError(branch)

connector.generate_migration(branch)
session.flush()

upgrade_exception = None
try:
    connector.upgrade(branch.commits)
except MigrationError as exc:
    downgrade_commits = exc.success_commits
    upgrade_exception = exc
else:
    downgrade_commits = branch.commits

try:
    connector.downgrade(branch.commits)
except MigrationError as exc:
    # TODO: Бля, ну пиздец, удаляем все запоротые таблицы и создаем их заново
    # Реализовывать не надо, но туду оставь
    raise "Фатальная шибка, что не получилось поднять и потом не получилось вернуть обратно"

if upgrade_exception:
    raise upgrade_exception
```

_Только дословно все не воспринимай, я пишу с нуля псевдокод, не обязательно все названия и типы передавать именно так_

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/branch.py
>      session.query(Branch).filter(Branch.id == branch.id).update({"type": BranchTypes.MR})
Эти 2 строки делают одно и то же

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/branch.py
>      s = session.query(Commit).filter(Commit.branch_id == branch.id).order_by(Commit.id).all()
Сюда тот же комментарий, что у мердж реквеста

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/branch.py
> +    result = session.query(Branch).filter(Branch.id == id).one()
Ты написал 1 в 1 то же самое 
Если по этому id ничего не найдется – будет exception
Либо ты тут имел в виду `one_or_none()`, либо тебе надо обрабатывать ошибку на уровне выше
И второе, наверное, мне нравится больше

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/branch.py
> +    return True
Очень тяжело читается 
Давай к бранчу добавим методы "коммиты, начиная с..." (`branch.commits_from(commit)`), "первый коммит ветки" (`branch.first_commit`)

Тогда этот метод превратится в:
```python
main = get_branch(1, session=session)  # Кстати, мы уверены, что MAIN первая ветка?*
entities_changed_branch = set()
entities_changed_main = set()

for c in branch.commits_from(branch.first_commit):
    entities_changed_branch.add((c.attribute_in or c.attribute_out).entity.id)

for c in main.commits_from(branch.first_commit):
    entities_changed_branch.add((c.attribute_in or c.attribute_out).entity.id)

if len(entities_changed_branch & entities_changed_main) != 0:
     return False
return True
```

Согласись, проще читается?

_* Если не очень уверены, давай соорудим статик метод `Branch.get_main()`, который вернет мэин_

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/branch.py
> +    return name1, name2
Ой что-то сложное и непонятное
Оно точно должно быть удостоено глобальной функции?

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/branch.py
> +    return tablename, name1, datatype1, name2, datatype2
Ой что-то сложное и непонятное
Оно точно должно быть удостоено глобальной функции?

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/branch.py
> +    return result
Не вижу ни одного использования

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/column.py
> +    name = name_converter(name)
АХАХАХАХАХ
Это что и зачем?

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/column.py
> +    while True:
Кажется, с ORM все циклы должны были уйти
ОСОБЕННО `while True`

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/converters.py
> +    return name.strip().replace(" ", "_")
Зачем?

2022-07-05 17:47 UTC, dyakovri commented on dbengine/methods/table.py
> +    name = name_converter(name)
Зачем?

2022-07-05 17:47 UTC, dyakovri commented on dbengine/models/branch.py
> +    POSTGRESQL = "postgresql"
Почему он в бранчах?

2022-07-05 17:47 UTC, dyakovri commented on dbengine/models/branch.py
> +    POSTGRESQL = "postgresql"
Точно ли не стоило сделать словарь?
```python
{
    "postgresql": dbengine.db_connector.PostgresConnector
}
```

2022-07-05 17:47 UTC, dyakovri commented on dbengine/routes/branch.py
> +    raise NotSupportedSchemeError
Почитай про словарик выше
CONNECTOR_DICT[settings.DWH_CONNECTION_PROD.scheme] выглядит малость лучше кучи if :)

2022-07-05 17:47 UTC, dyakovri commented on dbengine/routes/branch.py
> +    raise NotSupportedSchemeError
Кстати, почему это в бранчах?

2022-07-05 17:47 UTC, dyakovri commented on tests/__init__.py
> +prod_connector.connect()
А может стоит это сделать в ините?

2022-07-06 04:11 UTC, semen603089 commented on dbengine/methods/branch.py
> +    result = session.query(Branch).filter(Branch.id == id).one()
Вообще я тут имел ввиду one_or_none() ибо там потом если не найдено -> raise BranchNotFoundError
И уже она обрабатывается везде выше, где вызывается метод

2022-07-06 04:20 UTC, semen603089 commented on dbengine/methods/branch.py
> +    result = session.query(Branch).filter(Branch.id == id).one()
в routes/branch например 
    try:
        return get_branch(branch_id, session=db.session)
    except BranchNotFoundError:
        raise HTTPException(status_code=404, detail="Branch not found")

2022-07-06 04:24 UTC, semen603089 commented on dbengine/methods/branch.py
> +    result = session.query(Branch).filter(Branch.id == id).one()
в routes/branch например
`try:`
`    return get_branch(branch_id, session=db.session)`
`except BranchNotFoundError:`
`    raise HTTPException(status_code=404, detail="Branch not found")`

2022-07-06 04:30 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return True
Мы уверены, что main - первая ветка тк без нее новые не создадутся
methods/branch/create_branch:

`    s = session.query(Branch).filter(Branch.type == BranchTypes.MAIN).one_or_none()`
`    if not s:`
`        raise BranchError("Main branch does not exists")`

2022-07-06 04:32 UTC, semen603089 commented on dbengine/methods/column.py
> +    name = name_converter(name)
джунов кибербуллят ;(

2022-07-06 05:06 UTC, semen603089 commented on dbengine/models/branch.py
> +    POSTGRESQL = "postgresql"
перенес в db_connector

2022-07-06 05:07 UTC, semen603089 commented on dbengine/routes/branch.py
> +    raise NotSupportedSchemeError
Сделал через словарь, но если в base переносить то будет циклический импорт ибо в base branch_router импортируется, так что пока что в бранче оставил создание

2022-07-06 05:19 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return name1, name2
Это нужно чтобы генерить запросы к базе
А куда тогда стоит ее убрать? В класс из db_connector?

2022-07-06 05:19 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return tablename, name1, datatype1, name2, datatype2
Это нужно чтобы генерить запросы к базе
А куда тогда стоит ее убрать? В класс из db_connector?

2022-07-09 00:25 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return name1, name2
Сделал приватными методами IDbConnector'a

2022-07-09 00:26 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return tablename, name1, datatype1, name2, datatype2
Сделал приватным методом IDbConnector'a

2022-07-10 04:53 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return True
Если понимать метод commits_from как проход вверх по дереву тогда так просто сделать не получится я думаю

2022-07-10 04:55 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return True
во первых у атрибута нет поля entity, но это ладно еще 
branch.commits_from(branch.first_commit) вернет все коммиты из мейна до создания ветки, они нас вообще не интересуют, нам нужны кометы в ветке до первого

2022-07-10 04:56 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return True
такая штука сработает только есть commits_from это проход вниз по дереву

2022-07-10 08:39 UTC, semen603089 commented on dbengine/methods/branch.py
> +    return True
В общем я там добавил всяких штучек немного других но суть та же

2022-07-11 04:51 UTC, semen603089 commented on dbengine/methods/branch.py
> +            raise MergeError
Сделал методы upgrade и downgrade. Первый берет лист комиков и возвращает rollback - в случае успешного прохода просто все команды в обратном порядке. Второй берет лист строк и просто запускает их

2022-07-11 04:51 UTC, semen603089 commented on dbengine/methods/branch.py
>      s = session.query(Commit).filter(Commit.branch_id == branch.id).order_by(Commit.id).all()
Сделал методы upgrade и downgrade. Первый берет лист комиков и возвращает rollback - в случае успешного прохода просто все команды в обратном порядке. Второй берет лист строк и просто запускает их

2022-07-11 16:10 UTC, dyakovri commented on dbengine/db_connector/db_connector.py
> +CONNECTOR_DICT: Final = {"postgresql": PostgreConnector}
Это что за аннотация `Final`? Может `Dict[str, IDbConnector]`? 
Ну или `Final[Dict[str, IDbConnector]]`

2022-07-11 16:17 UTC, semen603089 commented on dbengine/db_connector/db_connector.py
> +CONNECTOR_DICT: Final = {"postgresql": PostgreConnector}
я гений просто

2022-07-11 16:27 UTC, dyakovri approved these changes

2022-07-11 16:27 UTC, merged